const fs = require('fs');
const path = require('path');

describe('룰렛 오버레이 레이아웃 회귀 방지', () => {
  const serverIndex = fs.readFileSync(path.join(__dirname, '..', 'server', 'index.js'), 'utf8');
  const rouletteViewer = fs.readFileSync(path.join(__dirname, '..', 'src', 'components', 'RouletteViewer.tsx'), 'utf8');
  const rouletteWheelSkins = fs.readFileSync(path.join(__dirname, '..', 'src', 'components', 'rouletteWheelSkins.tsx'), 'utf8');
  const rouletteWheelUtils = fs.readFileSync(path.join(__dirname, '..', 'src', 'components', 'rouletteWheelUtils.ts'), 'utf8');
  const rouletteThemeMaterials = fs.readFileSync(path.join(__dirname, '..', 'src', 'components', 'rouletteThemeMaterials.ts'), 'utf8');
  const rouletteThemeAtmosphere = fs.readFileSync(path.join(__dirname, '..', 'src', 'components', 'rouletteThemeAtmosphere.tsx'), 'utf8');
  const roulettePage = fs.readFileSync(path.join(__dirname, '..', 'src', 'features', 'admin', 'roulette-page.tsx'), 'utf8');
  const adminActionDialogs = fs.readFileSync(path.join(__dirname, '..', 'src', 'features', 'admin', 'admin-action-dialogs.tsx'), 'utf8');

  test('관리자 페이지는 릴/휠 표현 형태를 별도 선택으로 저장해야 함', () => {
    expect(roulettePage).toContain('ROULETTE_LAYOUT_OPTIONS');
    expect(roulettePage).toContain('ROULETTE_SKIN_OPTIONS');
    expect(roulettePage).toContain('표현 형태');
    expect(roulettePage).toContain('스킨');
    expect(roulettePage).toContain('실제 데이터 사용');
    expect(roulettePage).toContain('RouletteThemeSwatch');
    expect(roulettePage).toContain('릴 형태');
    expect(roulettePage).toContain('휠 형태');
    expect(roulettePage).toContain('프리즘');
    expect(roulettePage).toContain('스튜디오');
    expect(roulettePage).toContain('오로라');
    expect(roulettePage).toContain('벨벳');
    expect(roulettePage).toContain('모노');
    expect(roulettePage).toContain('아르데코');
    expect(roulettePage).toContain('크리스탈');
    expect(roulettePage).toContain('수묵');
    expect(roulettePage).toContain('노바');
    expect(roulettePage).toContain('세라믹');
    expect(roulettePage).toContain('아케이드');
    expect(roulettePage).toContain('오션');
    expect(roulettePage).toContain('솔라');
    expect(roulettePage).toContain('네온');
    expect(roulettePage).toContain('골드');
    expect(roulettePage).toContain('theme: `${layout}:${theme}`');
    expect(adminActionDialogs).toContain('ROULETTE_LAYOUT_OPTIONS');
    expect(adminActionDialogs).toContain('ROULETTE_SKIN_OPTIONS');
    expect(adminActionDialogs).toContain('표현 형태');
    expect(adminActionDialogs).toContain('스킨');
    expect(adminActionDialogs).toContain('RouletteThemeSwatch');
    expect(adminActionDialogs).toContain('theme: `${layout}:${skin}`');
  });

  test('서버는 테마 문자열에서 레이아웃과 컬러 테마를 함께 정규화해야 함', () => {
    const start = serverIndex.indexOf('function normalizeRouletteDefinition');
    const end = serverIndex.indexOf('function makeQuickStartCommandRules', start);
    const body = serverIndex.slice(start, end);

    expect(body).toContain("const allowedLayouts = new Set(['reel', 'wheel'])");
    expect(body).toContain("'studio'");
    expect(body).toContain("'prism'");
    expect(body).toContain("'aurora'");
    expect(body).toContain("'velvet'");
    expect(body).toContain("'mono'");
    expect(body).toContain("'deco'");
    expect(body).toContain("'crystal'");
    expect(body).toContain("'ink'");
    expect(body).toContain("'nova'");
    expect(body).toContain("'ceramic'");
    expect(body).toContain("'arcade'");
    expect(body).toContain("'ocean'");
    expect(body).toContain("'solar'");
    expect(body).toContain('const parsedLayout = themeParts.find((part) => allowedLayouts.has(part))');
    expect(body).toContain('`${parsedLayout}:${parsedTheme}`');
  });

  test('오버레이는 릴/휠 레이아웃을 파싱하고 분리 렌더링해야 함', () => {
    expect(rouletteViewer).toContain("type RouletteLayout = 'reel' | 'wheel'");
    expect(rouletteViewer).toContain('function parseRouletteLook');
    expect(rouletteViewer).toContain("const layout: RouletteLayout = urlLook.layout || serverLayout || 'reel'");
    expect(rouletteViewer).toContain('const t = ROULETTE_SKINS[theme] || ROULETTE_SKINS.studio');
    expect(rouletteViewer).toContain("...t.css");
    expect(rouletteViewer).toContain('...themeMaterial.css');
    expect(rouletteViewer).toContain('RouletteThemeAtmosphere');
    expect(rouletteViewer).toContain('data-roulette-theme={t.id}');
    expect(rouletteViewer).toContain('roulette-result-lock');
    expect(rouletteViewer).toContain("layout === 'wheel'");
    expect(rouletteViewer).toContain('renderReelWindow()');
  });

  test('휠 라벨과 섹터는 실제 항목 수를 기준으로 동적 렌더링해야 함', () => {
    expect(rouletteViewer).toContain('wheelLabelLines');
    expect(rouletteViewer).toContain('WheelSelectedSegment');
    expect(rouletteViewer).toContain('WheelSegmentsSvg');
    expect(rouletteViewer).toContain('WheelSkinOrnaments');
    expect(rouletteViewer).toContain('WheelGlassOverlay');
    expect(rouletteViewer).toContain('WheelPointer');
    expect(rouletteViewer).toContain('WheelLabelsSvg');
    expect(rouletteViewer).toContain('wheelSelectedIndex');
    expect(rouletteViewer).toContain('wheelRotationDeg');
    expect(rouletteViewer).toContain('wheelSettled');
    expect(rouletteViewer).toContain('WHEEL_STOP_EDGE_PADDING_RATIO');
    expect(rouletteViewer).toContain('function randomWheelStopOffsetRatio');
    expect(rouletteViewer).toContain('function wheelStopRotationForIndex');
    expect(rouletteViewer).toContain('function wheelIndexAtPointer');
    expect(rouletteViewer).toContain('function equivalentForwardRotation');
    expect(rouletteViewer).toContain('function buildWheelItemsForResult');
    expect(rouletteViewer).toContain('const nextWheelItems = buildWheelItemsForResult(pool, finalLabel, wheelTargetIndex)');
    expect(rouletteViewer).toContain('wheelStopRotationForIndex(wheelTargetIndex, nextWheelItems.length, wheelStopOffsetRatio)');
    expect(rouletteViewer).toContain('const wheelResolvedIndex = wheelIndexAtPointer(wheelFinalRotation, nextWheelItems.length)');
    expect(rouletteViewer).toContain('setWheelSelectedIndex(wheelResolvedIndex)');
    expect(rouletteViewer).toContain('wheelDiscRef');
    expect(rouletteViewer).toContain('wheel.animate(');
    expect(rouletteViewer).not.toContain('setWheelRotationDeg(currentWheelRotation)');
    expect(rouletteViewer).toContain('wheelSettled ? wheelSelectedIndex : -1');
    expect(rouletteViewer).toContain("{wheelSettled ? (state.label || state.value || '') : '회전 중'}");
    expect(rouletteViewer).not.toContain('WHEEL_SEGMENT_COUNT');
    expect(rouletteViewer).not.toContain('WHEEL_FALLBACK_ITEMS');
    expect(rouletteViewer).not.toContain('테스트 시청자');
    expect(rouletteViewer).toContain('segmentCount={wheelCount}');
    expect(rouletteViewer).not.toContain('const wheelRotation = offsetRows * 24');
    expect(rouletteWheelUtils).toContain('function splitWheelLabel');
    expect(rouletteWheelUtils).toContain('const splitAt = Math.ceil(parts.length / 2)');
    expect(rouletteWheelSkins).toContain('textAnchor="middle"');
    expect(rouletteWheelSkins).toContain('dominantBaseline="middle"');
    expect(rouletteWheelSkins).toContain('paintOrder="stroke fill"');
    expect(rouletteWheelSkins).not.toContain('filter="url(#rouletteWheelTextShadow)"');
    expect(rouletteWheelSkins).toContain('React.useId()');
    expect(rouletteWheelSkins).toContain('function texturePattern');
    expect(rouletteWheelSkins).toContain('function FamilyMotif');
    expect(rouletteWheelSkins).toContain('fontFamily="var(--roulette-font-display)"');
    expect(rouletteWheelSkins).toContain('data-wheel-theme={themeId}');
    expect(rouletteWheelSkins).toContain('data-pointer-theme={themeId}');
    expect(rouletteWheelSkins).toContain('function segmentPath');
    expect(rouletteWheelSkins).toContain('segmentCount');
    expect(rouletteWheelSkins).toContain('const segmentDeg = 360 / count');
    expect(rouletteWheelSkins).toContain('Array.from({ length: count })');
    expect(rouletteWheelSkins).toContain('roulette-wheel-ornaments');
    expect(rouletteThemeMaterials).toContain('const materials: Record<string, RouletteThemeMaterial>');
    expect(rouletteThemeMaterials).toContain("atmosphere: 'precision'");
    expect(rouletteThemeMaterials).toContain("atmosphere: 'spectrum'");
    expect(rouletteThemeMaterials).toContain("atmosphere: 'aurora'");
    expect(rouletteThemeMaterials).toContain("atmosphere: 'deco'");
    expect(rouletteThemeMaterials).toContain("atmosphere: 'crystal'");
    expect(rouletteThemeMaterials).toContain("atmosphere: 'ink'");
    expect(rouletteThemeMaterials).toContain("atmosphere: 'nova'");
    expect(rouletteThemeMaterials).toContain("atmosphere: 'ceramic'");
    expect(rouletteThemeMaterials).toContain("atmosphere: 'arcade'");
    expect(rouletteThemeMaterials).toContain("atmosphere: 'sakura'");
    expect(rouletteThemeMaterials).toContain("atmosphere: 'ocean'");
    expect(rouletteThemeMaterials).toContain("atmosphere: 'solar'");
    expect(rouletteThemeMaterials).toContain("atmosphere: 'cyber'");
    expect(rouletteThemeMaterials).toContain("atmosphere: 'gold'");
    expect(rouletteThemeAtmosphere).toContain('prefers-reduced-motion:reduce');
  });
});
