export type BrushType = 'pen' | 'pencil' | 'crayon' | 'brush' | 'marker' | 'highlighter' | 'airbrush' | 'watercolor' | 'eraser';
export type DrawingBrush = { type: BrushType; version: number; color: string; alpha: number; size: number; texture: number; hardness: number; flow: number; angle: number; smoothing: number };
export type DrawingPoint = { x: number; y: number; p: number; t: number };
export type DrawingKind = 'freehand' | 'line' | 'rectangle' | 'ellipse' | 'star' | 'heart' | 'fill' | 'selection';
export type SelectionFrame = { t: number; x: number; y: number; scaleX: number; scaleY: number; angle: number; quad?: number[] };
export type SelectionRect = { x: number; y: number; width: number; height: number };
export type DrawingShapeStyle = { fillEnabled: boolean; fillColor: string; fillAlpha: number; strokeEnabled: boolean };
export type DrawingStroke = { id: string; layerId: string; seed: number; brush: DrawingBrush; points: DrawingPoint[]; kind: DrawingKind; transform: { x: number; y: number; scale: number }; mirror: boolean; mirrorY?: boolean; runs?: number[]; selection?: { rect: SelectionRect; sourceId: string | null; copy: boolean }; frames?: SelectionFrame[]; shape?: DrawingShapeStyle };
export type DrawingLayer = { id: string; name: string; visible: boolean; locked: boolean };
export type DrawingDocument = { version: number; rendererVersion: string; id: string; revision: number; width: number; height: number; layers: DrawingLayer[]; strokes: DrawingStroke[]; replayMode: 'drawing-only' | 'original' | 'trim-gaps' };
export type DrawingTimeline = { entries: { id: string; start: number; end: number; offset: number }[]; speed: number; sourceDurationMs: number; targetReplayMs: number; mode: string };
export const DRAWING_VERSION: number;
export const RENDERER_VERSION: string;
export const MAX_DOCUMENT_BYTES: number;
export const BRUSHES: Record<BrushType, { label: string; size: number; texture: number; hardness: number; flow: number; angle: number }>;
export function createBrush(type?: BrushType, color?: string, alpha?: number): DrawingBrush;
export function rememberDrawingColor(colors: string[], stroke?: DrawingStroke): string[];
export function createDrawing(widthRatio?: number, heightRatio?: number, id?: string): DrawingDocument;
export function drawingFromItem(item: unknown): DrawingDocument | null;
export function canonicalDrawing(value: unknown): string;
export function hashDrawing(document: DrawingDocument): Promise<string>;
export function validateDrawing(document: unknown, limits?: { maxStrokes?: number; maxPoints?: number }): { pointCount: number; rawPointCount: number; jsonSize: number; strokeCount: number };
export function visibleStrokes(document: DrawingDocument): DrawingStroke[];
export function drawingInk(document: DrawingDocument): { raw: number; units: number };
export function drawingCost(document: DrawingDocument, settings: { pricingMode: string; costPoints: number; inkCostPerUnit: number }): number;
export function buildTimeline(document: DrawingDocument, maxSeconds?: number): DrawingTimeline;
export function pointsAtTime(points: DrawingPoint[], time?: number): DrawingPoint[];
