import {
  Cable,
  Coins,
  Gift,
  HeartHandshake,
  Home,
  ListChecks,
  LifeBuoy,
  MessageSquare,
  Orbit,
  PlaySquare,
  Settings,
  ShieldCheck,
  Sparkles,
  Timer,
  UserRound,
  Vote,
  Workflow,
} from 'lucide-react';

export const adminNav = [
  { href: '/dashboard', label: '홈', icon: Home },
  { href: '/arubot-admin', label: 'AruBot 관리자', icon: ShieldCheck, adminOnly: true },
  { href: '/connection', label: '플랫폼 연결', icon: Cable },
  { href: '/commands', label: '채팅 명령어', icon: MessageSquare },
  { href: '/macros', label: '자동 알림', icon: Timer },
  { href: '/points', label: '시청자 포인트', icon: Coins },
  { href: '/logs', label: '이벤트 로그', icon: ListChecks },
  { href: '/predictions', label: '예측 베팅', icon: Vote },
  { href: '/automations', label: '방송 자동화', icon: Orbit },
  { href: '/actions', label: '실행 액션', icon: Workflow },
  { href: '/video-donations/queue', label: '영상 후원', icon: PlaySquare },
  { href: '/roulette', label: '룰렛', icon: Sparkles },
  { href: '/donations/rules', label: '후원 반응', icon: Gift },
  { href: '/viewer/me', label: '시청자 페이지', icon: UserRound },
];

export const adminFeatureMap = {
  connection: {
    title: '플랫폼 연결',
    description: 'CHZZK, CIME, YouTube 채널을 한곳에서 연결합니다.',
    endpoint: '/api/auth/session',
    icon: Cable,
    actions: [],
    tips: ['방송 채널을 한곳에 모아요', '플랫폼별 시청자를 함께 맞이해요', '연결한 순간 참여 기능이 열려요'],
  },
  commands: {
    title: '채팅 명령어',
    description: '시청자가 궁금한 순간 채팅에서 바로 답을 얻고 참여할 수 있게 해요.',
    endpoint: '/api/bot/rules',
    icon: MessageSquare,
    actions: [{ href: '/variables', label: '사용 가능한 변수' }],
    tips: ['반복 질문에 빠르게 답해요', '채팅이 산만해지지 않게 조절해요', '포인트로 참여 명령어를 만들어요'],
  },
  macros: {
    title: '자동 알림',
    description: '중요한 공지를 필요한 타이밍에 채팅으로 보여줘요.',
    endpoint: '/api/macros',
    icon: Timer,
    actions: [],
    tips: ['공지 타이밍을 놓치지 않아요', '과하지 않게 반복돼요', '시청자가 필요한 안내를 쉽게 봐요'],
  },
  points: {
    title: '시청자 포인트',
    description: '채팅 참여가 포인트로 쌓이고, 다시 룰렛과 이벤트 참여로 이어지게 해요.',
    endpoint: '/api/channelpoints/list',
    icon: Coins,
    actions: [
      { href: '/points/import', label: '가져오기' },
      { href: '/points/export', label: '내보내기' },
    ],
    tips: ['재방문할 이유를 만들어요', '열심히 참여한 시청자가 보입니다', '이벤트 참여가 더 쉬워져요'],
  },
  predictions: {
    title: '예측 베팅',
    description: '방송의 중요한 순간을 시청자가 포인트로 함께 고르고 응원하게 해요.',
    endpoint: '/api/predictions',
    icon: Vote,
    actions: [{ href: '/predictions', label: '예측 열기' }],
    tips: ['!투표로 바로 참여해요', '선택지는 방송 상황에 맞게 자유롭게 열어요', '화면에 현재 분위기가 살아나요'],
  },
  automations: {
    title: '방송 자동화',
    description: '채팅과 후원 순간이 TTS, 사운드, T.I.T.S. 연출로 바로 이어지게 해요.',
    endpoint: '/api/automations/overview',
    icon: Orbit,
    actions: [{ href: '/automations', label: '자동화 열기' }],
    tips: ['방송 PC 도구를 버튼처럼 실행해요', '후원과 이벤트 순간에 연출이 따라와요', '복잡한 장면 전환을 한 번에 묶어요'],
  },
  actions: {
    title: '실행 액션',
    description: '채팅, 포인트, 후원, 화면 연출을 원하는 순서로 이어 방송 액션을 만듭니다.',
    endpoint: '/api/automations/overview',
    icon: Workflow,
    actions: [{ href: '/variables', label: '특수 변수 보기' }],
    tips: ['룰렛 결과가 바로 연출로 이어져요', '조건에 따라 다른 반응을 만들어요', '버튼 하나로 여러 동작을 실행해요'],
  },
  videoDonations: {
    title: '영상 후원',
    description: '시청자가 신청한 영상을 보기 좋게 줄 세우고 방송 화면에 자연스럽게 띄워요.',
    endpoint: '/api/video-donation/queue',
    icon: PlaySquare,
    actions: [],
    tips: ['신청 순서가 한눈에 보여요', '긴 영상은 재생 시간을 조절해요', 'OBS에서 바로 재생돼요'],
  },
  roulette: {
    title: '룰렛',
    description: '포인트와 후원을 기대감 있는 당첨 순간으로 바꿔 채팅을 더 뜨겁게 해요.',
    endpoint: '/api/roulette/definitions',
    icon: Sparkles,
    actions: [
      { href: '/roulette/logs', label: '결과 보기' },
      { href: '/roulette/viewer', label: 'OBS 주소' },
    ],
    tips: ['당첨 항목을 방송 분위기에 맞춰요', '결과가 화면에 바로 떠요', '다시 보고 싶은 순간을 남겨요'],
  },
  donations: {
    title: '후원 반응',
    description: '후원 순간에 어울리는 답변과 연출로 시청자의 마음을 더 크게 받아요.',
    endpoint: '/api/donation/rules',
    icon: HeartHandshake,
    actions: [],
    tips: ['후원 메시지가 더 특별해져요', '금액별 감사 표현을 다르게 보여줘요', '채팅과 화면 반응이 함께 나와요'],
  },
  variables: {
    title: '치환 변수',
    description: '닉네임, 포인트, 후원 정보를 넣어 시청자에게 직접 말하는 답변을 만들어요.',
    endpoint: '/api/bot/settings',
    icon: MessageSquare,
    actions: [{ href: '/commands', label: '명령어로 돌아가기' }],
    tips: ['시청자 이름을 불러줘요', '후원과 룰렛 문구도 생동감 있게 바꿔요', '자주 쓰는 표현을 쉽게 골라요'],
  },
  diagnostics: {
    title: '도움말',
    description: '방송 준비 중 막히는 지점을 빠르게 찾아 바로 이어갈 수 있게 돕습니다.',
    endpoint: '/api/platforms/status',
    icon: LifeBuoy,
    actions: [
      { href: '/connection', label: '연결 다시 보기' },
    ],
    tips: ['문제가 있을 때만 열어보면 돼요', '막힌 연결을 빠르게 찾아요', '필요한 설정으로 바로 이동해요'],
  },
  settings: {
    title: '설정',
    description: '내 방송 말투와 참여 방식에 맞게 AruBot의 기본 분위기를 맞춰요.',
    endpoint: '/api/bot/settings',
    icon: Settings,
    actions: [{ href: '/connection', label: '플랫폼 연결' }],
    tips: ['봇 말투를 방송 스타일에 맞춰요', '시청자에게 보여줄 화면을 고릅니다', 'OBS에 띄울 화면을 쉽게 찾습니다'],
  },
  live: {
    title: '오늘 방송',
    description: '방송 시작 전 필요한 참여 기능을 빠르게 열고 준비해요.',
    endpoint: '/api/platforms/status?refresh=true',
    icon: Home,
    actions: [{ href: '/connection', label: '플랫폼 연결' }],
    tips: ['방송 전 체크가 빨라져요', '오늘 쓸 이벤트를 바로 꺼내요', '시청자에게 보여줄 페이지를 준비해요'],
  },
  bot: {
    title: 'AruBot',
    description: '채팅 참여, 포인트, 이벤트 연출을 함께 관리합니다.',
    endpoint: '/api/bot/stats',
    icon: LifeBuoy,
    actions: [{ href: '/connection', label: '플랫폼 연결' }],
    tips: ['채팅 반응을 자동화해요', '시청자 참여를 포인트로 이어요', '방송 화면에 참여형 이벤트를 띄워요'],
  },
};

export type AdminFeatureKey = keyof typeof adminFeatureMap;
