import {
  Cable,
  Coins,
  Gift,
  HeartHandshake,
  Home,
  LifeBuoy,
  MessageSquare,
  Orbit,
  PlaySquare,
  Settings,
  Sparkles,
  Timer,
  Vote,
} from 'lucide-react';

export const adminNav = [
  { href: '/dashboard', label: '홈', icon: Home },
  { href: '/connection', label: '플랫폼 연결', icon: Cable },
  { href: '/commands', label: '채팅 명령어', icon: MessageSquare },
  { href: '/macros', label: '자동 알림', icon: Timer },
  { href: '/points', label: '시청자 포인트', icon: Coins },
  { href: '/predictions', label: '예측 베팅', icon: Vote },
  { href: '/automations', label: '방송 자동화', icon: Orbit },
  { href: '/video-donations/queue', label: '영상 후원', icon: PlaySquare },
  { href: '/roulette', label: '룰렛', icon: Sparkles },
  { href: '/donations/rules', label: '후원 반응', icon: Gift },
  { href: '/settings', label: '설정', icon: Settings },
];

export const adminFeatureMap = {
  connection: {
    title: '플랫폼 연결',
    description: 'CHZZK와 CIME 채널을 연결하고 방송에서 사용할 봇 기능을 켜세요.',
    endpoint: '/api/auth/session',
    icon: Cable,
    actions: [{ href: '/settings', label: '설정 열기' }],
    tips: ['채널별 계정을 연결해요', '다른 플랫폼을 나중에 추가할 수 있어요', '연결 후 기능 카드가 바로 활성화돼요'],
  },
  commands: {
    title: '채팅 명령어',
    description: '시청자가 채팅으로 바로 쓸 수 있는 응답, 안내, 포인트 사용 규칙을 만들어요.',
    endpoint: '/api/bot/rules',
    icon: MessageSquare,
    actions: [{ href: '/variables', label: '사용 가능한 변수' }],
    tips: ['반복 질문을 자동으로 안내해요', '권한과 쿨다운을 정할 수 있어요', '포인트 차감 명령어도 만들 수 있어요'],
  },
  macros: {
    title: '자동 알림',
    description: '방송 중 반복 안내, 예약 공지, 채팅 리마인드를 부드럽게 보내요.',
    endpoint: '/api/macros',
    icon: Timer,
    actions: [],
    tips: ['방송 공지를 잊지 않게 도와줘요', '반복 간격과 사용 여부를 관리해요', '채팅 흐름에 맞춰 부담 없이 노출해요'],
  },
  points: {
    title: '시청자 포인트',
    description: '시청 참여를 포인트로 쌓고, 보상과 룰렛 참여로 자연스럽게 이어지게 해요.',
    endpoint: '/api/channelpoints/list',
    icon: Coins,
    actions: [
      { href: '/points/import', label: '가져오기' },
      { href: '/points/export', label: '내보내기' },
    ],
    tips: ['채팅 참여에 포인트를 지급해요', '시청자별 잔액을 빠르게 확인해요', '보상 이벤트와 연결하기 좋아요'],
  },
  predictions: {
    title: '예측 베팅',
    description: '시청자가 방송의 결과를 포인트로 예측하고, 정산 결과를 채팅과 OBS 화면에서 함께 확인해요.',
    endpoint: '/api/predictions',
    icon: Vote,
    actions: [{ href: '/predictions', label: '예측 열기' }],
    tips: ['채팅 명령어로 바로 참여해요', '선택지는 2개 이상 자유롭게 만들 수 있어요', 'OBS 오버레이로 현재 비율을 보여줘요'],
  },
  automations: {
    title: '방송 자동화',
    description: '후원, 채팅, 포인트 이벤트를 OBS, T.I.T.S., 투네이션, TTS, 제어 버튼과 연결해 방송 연출을 자동으로 실행해요.',
    endpoint: '/api/automations/overview',
    icon: Orbit,
    actions: [{ href: '/automations', label: '자동화 열기' }],
    tips: ['오라클 직접 연동과 로컬 프로그램 모드를 선택해요', '민감한 키는 로컬에만 저장해요', '사운드는 기본 10MB까지 서버에 보관해요'],
  },
  videoDonations: {
    title: '영상 후원',
    description: '시청자가 보낸 영상을 순서대로 받고, 방송 화면에 안정적으로 재생해요.',
    endpoint: '/api/video-donation/queue',
    icon: PlaySquare,
    actions: [{ href: '/video-donations/viewer', label: 'OBS 주소' }],
    tips: ['요청 순서를 관리해요', '재생 시간을 제한할 수 있어요', 'OBS 브라우저 소스로 바로 연결해요'],
  },
  roulette: {
    title: '룰렛',
    description: '포인트와 후원을 방송 이벤트로 바꿔주는 참여형 룰렛을 만들어요.',
    endpoint: '/api/roulette/definitions',
    icon: Sparkles,
    actions: [
      { href: '/roulette/logs', label: '결과 보기' },
      { href: '/roulette/viewer', label: 'OBS 주소' },
    ],
    tips: ['아이템과 확률을 조절해요', '당첨 결과를 방송 화면에 띄워요', '실행 기록을 확인할 수 있어요'],
  },
  donations: {
    title: '후원 반응',
    description: '후원 금액과 메시지에 맞춰 채팅 답변, 포인트 지급, 연출을 자동으로 실행해요.',
    endpoint: '/api/donation/rules',
    icon: HeartHandshake,
    actions: [],
    tips: ['후원 메시지에 맞춰 반응해요', '금액 구간별 보상을 만들 수 있어요', '방송 연출과 함께 쓰기 좋아요'],
  },
  variables: {
    title: '치환 변수',
    description: '채팅 답변에 닉네임, 포인트, 후원 정보를 자연스럽게 넣어보세요.',
    endpoint: '/api/bot/settings',
    icon: MessageSquare,
    actions: [{ href: '/commands', label: '명령어로 돌아가기' }],
    tips: ['개인화된 답변을 만들어요', '후원과 룰렛 문구에도 사용할 수 있어요', '자주 쓰는 문구를 빠르게 확인해요'],
  },
  diagnostics: {
    title: '도움말',
    description: '연결이 잘 되지 않을 때 필요한 상태만 간단히 확인합니다.',
    endpoint: '/api/version',
    icon: LifeBuoy,
    actions: [
      { href: '/connection', label: '연결 다시 보기' },
      { href: '/settings', label: '설정 열기' },
    ],
    tips: ['문제가 있을 때만 열어보면 돼요', '연결 상태를 간단히 확인해요', '설정 화면으로 바로 이동할 수 있어요'],
  },
  settings: {
    title: '설정',
    description: '내 방송에 맞게 봇 이름, 기본 동작, 공개 화면 옵션을 정리해요.',
    endpoint: '/api/bot/settings',
    icon: Settings,
    actions: [{ href: '/connection', label: '플랫폼 연결' }],
    tips: ['방송 스타일에 맞춰 조정해요', '공개 페이지 표시를 관리해요', 'OBS 화면 주소를 한곳에서 관리해요'],
  },
  live: {
    title: '오늘 방송',
    description: '방송에 필요한 기능들을 한눈에 확인하고 바로 열어보세요.',
    endpoint: '/api/chzzk/live/me',
    icon: Home,
    actions: [{ href: '/connection', label: '플랫폼 연결' }],
    tips: ['방송 전 필요한 기능을 빠르게 열어요', '시청자 참여 기능을 준비해요', '공개 페이지와 OBS 화면을 연결해요'],
  },
  bot: {
    title: 'AruBot',
    description: '방송 채팅 참여와 운영 자동화를 한곳에서 관리합니다.',
    endpoint: '/api/bot/stats',
    icon: LifeBuoy,
    actions: [{ href: '/settings', label: '설정' }],
    tips: ['채팅 반응을 자동화해요', '시청자 참여를 포인트로 이어요', '방송 화면에 참여형 이벤트를 띄워요'],
  },
};

export type AdminFeatureKey = keyof typeof adminFeatureMap;
